- hosts: localhost
  become: true

  roles:
  - role: external_modules/yedit/roles/lib_yaml_editor
  - role: openshift-singlenode-config
    master_config_file: /data/origin/host-config-dir/master/master-config.yaml
    node_config_file: /data/origin/host-config-dir/node-localhost/node-config.yaml
