---
- name: set NodePort range
  yedit:
    src: "{{ master_config_file }}"
    key: kubernetesMasterConfig.servicesNodePortRange
    value: 20-34

- name: set node eviction policy (deactivated)
  yedit:
    src: "{{ node_config_file }}"
    key: kubeletArguments.eviction-hard
    value:
      - memory.available<500Mi
      - nodefs.available<500Mi
      - nodefs.inodesFree<100Mi
      - imagefs.available<100Mi
      - imagefs.inodesFree<100Mi
  when: false

- name: allow iptables external access on NodePorts
  iptables:
    chain: FORWARD
    jump: ACCEPT
